### ISSUE TITLE
Android.mk conflict

### ISSUE THREAD

**Issue by ghost** [vvb2060/BoringSSL_Android#5]
I can't compile due to conflict with Android.mk. What should I do?

`E:\modding\ImGUI\PolarImGui\app\build\.cxx\Debug\4i2n254r\prefab\arm64-v8a\prefab-configure\boringssl\Android.mk -> E:\modding\ImGUI\PolarImGui\app\build\.cxx\Debug\4i2n254r\prefab\arm64-v8a\prefab\boringssl\Android.mk: The destination file already exists.
`

**Comment by vvb2060** [comment]
Not our problem

**Comment by ghost** [comment]
Ok. I removed your boringssl, and the problem is solved
