### ISSUE TITLE
Gradle and CMake errors

### ISSUE THREAD

**Issue by shinxxxxwon** [vvb2060/BoringSSL_Android#7]
I read `README.md` and applied it to my project.  

**app/build.gradle**
```
...
buildFeatures {
        prefab true
    }

dependencies {
    implementation 'io.github.vvb2060.ndk:boringssl:4.0'
    implementation project(path: ':sdk')
    debugImplementation 'com.pspdfkit:pspdfkit:8.4.1'
    profileImplementation 'com.pspdfkit:pspdfkit:8.4.1'
    releaseImplementation 'com.pspdfkit:pspdfkit:8.4.1'
}
...


```

Since I use c and cpp files with `CMakeLists.txt`, I adopted the method using CMakeLists.txt.
```
cmake_minimum_required(VERSION 3.10)

add_library( nativeLib

             # Sets the library as a shared library.
             SHARED

             # Provides a relative path to your source file(s).
             src_my_c_or_cpp_file
            ...
             )

find_package(boringssl REQUIRED CONFIG)

find_library( log-lib
              GLESv1
              )

target_link_libraries( nativeLib
                       boringssl::crypto_static
                       android
                      )


```
Now when I compile the project I get an error:
```
Execution failed for task ':app:generateJsonModelDebug'.
 executing external native build for cmake /my_project_path/app/CMakeLists.txt
```
I need to use `boringssl` on android. Of course, it must be ported as a C file. The reason is that boringssl is required by the `IPP`-based printing library called `CUPS`. I tried to use `google/boringssl`, but the encryption algorithm in the code is implemented as `.pl (perl script)`, so an `undefined reference` error occurs when compiling.

Therefore, we are looking at your `git` and trying to apply it.

How do I resolve errors in Gradle and CMakeLists.txt?

**Comment by vvb2060** [comment]
https://source.android.com/docs/setup/contribute/report-bugs

**Comment by shinxxxxwon** [comment]
@vvb2060 
Are there any problems with the syntax of my `build.gradle` and `CMakeLists.txt`?

Do I need to use a specific version of JAVA, CMAKE, or Gradle?
