### ISSUE TITLE
[CXX1415] cpp-debug-vvb2060.abi 'vvb2060' is invalid. Valid values are 'armeabi-v7a, arm64-v8a, x86, x86_64'

### ISSUE THREAD

**Issue by MuhammadUsamaSiddiqui** [vvb2060/BoringSSL_Android#9]
Hi, I am using the following version of the dependencies in build.gradle file:
```
implementation "io.github.vvb2060.ndk:xposeddetector:2.2"
implementation "io.github.vvb2060.ndk:boringssl:3.0"
```
And getting the following error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':demo:configureNdkBuildDebug[arm64-v8a]'.
> [CXX1415] /Users/Desktop/Project/build/demo/.cxx/Debug/181k6z45/arm64-v8a/android_gradle_build.json debug|arm64-v8a : cpp-debug-vvb2060.abi 'vvb2060' is invalid. Valid values are 'armeabi-v7a, arm64-v8a, x86, x86_64'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
Error: Gradle task assembleDevDebug failed with exit code 1

**Comment by vvb2060** [comment]
Cannot Reproduce

**Comment by MuhammadUsamaSiddiqui** [comment]
I am using `ndkVersion '21.2.6472646'` and `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip`

**Comment by vvb2060** [comment]
try upgrade AGP

**Comment by MuhammadUsamaSiddiqui** [comment]
Still not fixed, after upgrading AGP.
